### ISSUE TITLE
Exception is thrown when I create a GameWindow using Monitors static property

### ISSUE THREAD

**Issue by santoro-mariano** [ForeverZer0/glfw-net#10]
Exception: 'Invalid window size 0x0' is thrown when I use Monitors static property in Glfw class to create a new GameWindow.

Code Example:
var monitor = Glfw.Monitors[1];
var videoMode = Glfw.GetVideoMode(monitor);
var window = new GameWindow(videoMode.Width, videoMode.Height, "Test", monitor, Window.None);

**Comment by Kharzette** [comment]
I'm getting that as well.  An entry point not found exception for glfwGetMonitorWorkarea

I'll see if I can figure it out

**Comment by santoro-mariano** [comment]
Hello @Kharzette,  I already fixed it in PR #11

**Comment by Kharzette** [comment]
Oh goody thanks!

**Comment by Kharzette** [comment]
Hmm mine was a little different I think.  I think my problem is that my shared library has no GetMonitorWorkarea function:

`kharzette@Linzette:~/.ssh$ nm -D /usr/lib/x86_64-linux-gnu/libglfw.so |grep 'Monitor'
0000000000007820 T glfwGetMonitorName
00000000000077a0 T glfwGetMonitorPhysicalSize
0000000000007730 T glfwGetMonitorPos
0000000000007650 T glfwGetMonitors
00000000000076d0 T glfwGetPrimaryMonitor
0000000000009ae0 T glfwGetWindowMonitor
000000000000cf10 T glfwGetX11Monitor
0000000000007880 T glfwSetMonitorCallback
0000000000009b40 T glfwSetWindowMonitor
kharzette@Linzette:~/.ssh$ 
`

I'll get your fix though and see if I can do without it.  I just want to let the user specify what monitor to create the window on for windowed mode.

**Comment by ForeverZer0** [comment]
@Kharzette 
This is closed with PR that @santoro-mariano submitted, as your issue seems slightly different. Not all platforms support work the concept of work areas (though very strange for the binary to not have an exported symbol for it....).
 
Do note that `GetMonitorWorkAreas` was added with the latest version 3.3, and your binary may be out of date. Can you confirm you are using latest version and not 3.2.1?

**Comment by ForeverZer0** [comment]
@santoro-mariano 
Just a side note, the `GameWindow` class is being deprecated for the more accurately named `NativeWindow` class. Currently is just a sub-class placeholder to maintain backwards compatibility, but will eventually be removed. Simply renaming to `NativeWindow` is completely safe to do without any other modifications.

**Comment by Kharzette** [comment]
oops
3.2.1 X11 GLX EGL clock_gettime /dev/js Xf86vm shared
