### ISSUE TITLE
GLFW does not contain the function Glfw.GetTime() 

### ISSUE THREAD

**Issue by SeoFernando25** [ForeverZer0/glfw-net#22]
The sample window creation code on README.md says 
```
using (var window = new NativeWindow(800, 600, "MyWindowTitle"))
            {
                // Main application loop
                while (!window.IsClosing)
                {
                    // OpenGL rendering
                    // Implement any timing for flow control, etc (see Glfw.GetTime())
                   
                    // Swap the front/back buffers
                    window.SwapBuffers();

                    // Poll native operating system events (must be called or OS will think application is hanging)
                    Glfw.PollEvents();
                }
            }
```

But the function Glfw.GetTime() does not appear to exist.

**Comment by ForeverZer0** [comment]
It is implemented as the property `Glfw.Time`, not as a function. I am unsure when that change was made, or if I was always that and I was incorrect to use it in an example. I do somewhat feel that that at the very least `GetTime` should be added simply for the sake of consistency, and will add that with the next update.
