### ISSUE TITLE
NativeWindow.OnFileDrop hardcoded for 32 bit pointers, crashes on 64 bit Windows

### ISSUE THREAD

**Issue by SirIntruder** [ForeverZer0/glfw-net#25]
So I had a crash in NativeWindow.OnFileDrop callback because of this line:

> var ptr = new IntPtr(Marshal.ReadInt32(pointer + offset));

which returned nonsense on my 64 bit windows machine. Issue can be fixed by replacing with

> var ptr = Marshal.ReadIntPtr(pointer + offset);

which reads native-sized pointers and should probably be used instead.

**Comment by ForeverZer0** [comment]
Thank you, just fixed in 297a522a9507ac93619ff27d15d58172acf6e232.

I totally thought I had already fixed this issue before, apparently I was wrong xD.
