### ISSUE TITLE
How do I get the Example projects to run?

### ISSUE THREAD

**Issue by EliasCK** [ForeverZer0/glfw-net#26]
Which glfw dll file do I need to use?
Which folder should I place it in?
Do I need to add anything in a csproj file?
The default right now is netcoreapp3.1

Tried out a bunch of variations, but none of them works. Also tried dumping it in next to the built exe, no luck.

**Comment by EliasCK** [comment]
Had to rename it to glfw.dll instead glfw3.dll, would be nice with a note of that in the readme :)

**Comment by ForeverZer0** [comment]
> Had to rename it to glfw.dll instead glfw3.dll, would be nice with a note of that in the readme :)

Do you mean the section labeled [IMPORTANT](https://github.com/ForeverZer0/glfw-net#important), xD?

Did you get it working now then?

**Comment by EliasCK** [comment]
Hehe yeah, did see the section but forgot about again when writing this in fustration haha, sorry.
I had to name it glfw not glfw3 (and I'm on Windows).

**Comment by myblindy** [comment]
> Do you mean the section labeled IMPORTANT, xD?

Just in case he wasn't clear, the section you name gives the exact wrong instruction, you have to rename *from* `glfw3.dll` *to* `glfw.dll`.
