### ISSUE TITLE
DllNotFoundException: Unable to load DLL 'glfw': The specified module could not be found

### ISSUE THREAD

**Issue by Deepvelooperz** [ForeverZer0/glfw-net#27]
![Annotation 2020-05-20 140325](https://user-images.githubusercontent.com/63566201/82410578-c6dd6900-9aa2-11ea-9e2a-01a4133f11a7.png)

**Comment by ForeverZer0** [comment]
The library names differ across platforms, and on Windows it needs to be `glfw3`, as explained [here](https://github.com/ForeverZer0/glfw-net#important).

The current version is targeting .NET Standard, and it is expected the user implements resolving native dependencies (i.e. NativeLibrary on .NET Core, dllmap on Mono, etc.) depending on their target. .NET Standard itself has no standardized method of loading native libraries that I feel are appropriate for public code or would assume appropriate for every project.

The next release is transitioning to .NET Core, where library resolving it will be handled internally and no action needs taken. There is some discussion regarding it in #21 and #24
