### ISSUE TITLE
Why GLFW.NET does't see the Vulkan?

### ISSUE THREAD

**Issue by rovecode** [ForeverZer0/glfw-net#33]
Why GLFW.NET does't see the Vulkan?

VulkanSharp can find Vulkan, but GLFW return _Vulkan.IsSupported_ __false__, and when try get Vulkan instance extensions throw _Vulkan: Loader not found_

What can I do to make the GLFW.NET see the Vulkan?

System: _MacOS Catalina_
Framework: _Net Core 3.1_

###### Best Regards, _Roman S_

**Comment by ForeverZer0** [comment]
This wrapper is simply calling the query function in the native GLFW library and returning the result, not actually doing any searching or loading itself. 

The GLFW provides a special note for macOS users regarding Vulkan and proper linking [here](https://www.glfw.org/docs/latest/vulkan_guide.html#vulkan_loader), which states:

macOS: Because the Vulkan loader and ICD are not installed globally on macOS, you need to set up the application bundle according to the LunarG SDK documentation. This is explained in more detail in the [SDK documentation for macOS](https://vulkan.lunarg.com/doc/sdk/1.2.141.2/mac/getting_started.html).

Is that helpful at all?

**Comment by rovecode** [comment]
Thanks. It's helped me.

GLFW now Vulkan.IsSupported return true, But when I try now get Vulkan extensions GLFW throw new error - "Attempted to read or write protected memory. This is often an indication that other memory is corrupt."

```c#

string[] extensions = GLFW.Vulkan.GetRequiredInstanceExtensions();

```

**Comment by rovecode** [comment]
I find answer. Exception is throw if I invoke __GLFW.Glfw.Init();__

**Comment by ForeverZer0** [comment]
That indeed seems like an error with this library, I will take a look into it.

**Comment by rovecode** [comment]
> That indeed seems like an error with this library, I will take a look into it.

Thanks. I would like to use your binding, because i think is best glfw c# binding now.

Thank you for spending time.

**Comment by rovecode** [comment]
> That indeed seems like an error with this library, I will take a look into it.

any updates on this?

**Comment by ForeverZer0** [comment]
Oh, my bad, completely slipped my mind on this. I am literally digging into right now and working on it. Sorry for the delay :/

**Comment by ForeverZer0** [comment]
Well, am kinda already scratching my head on what the issue could be. I don't have Mac to test it on, but on my Arch LInux machine.

Running this code:

```csharp
static void Main(string[] args)
{
    Glfw.Init();
    Console.WriteLine($"Vulkan: {Vulkan.IsSupported}");
    foreach (var extension in Vulkan.GetRequiredInstanceExtensions())
    {
        Console.WriteLine(extension);
    }
}
```

...gives me this:

```
Vulkan: True
VK_KHR_surface
VK_KHR_xcb_surface
```

I started digging into the code, and ensuring the methods was a proper analog of its C counterpart. 

The C methods is pretty straightforward:
```c
const char** glfwGetRequiredInstanceExtensions(uint32_t *count);
```

You call it, it returns a pointer to a an array of pointers, and writes the number of elements in the array to `count` so you know how many elements to read without getting a segfault, which would cause the `AccessViolationException`. The return value is essentially an a pointer to an `IntPtr[]`, where each pointer in the array is a pointer to a null-terminated string.

The C# code of this library appears to handle this properly, even when stepping through it line by line. I annotated it all to explain the logic step-by-step (my process for finding bugs)

```csharp
public static string[] GetRequiredInstanceExtensions()
{
    // Get the initial pointer where the C array is located in memory, and how many elements there are.
    var ptr = GetRequiredInstanceExtensions(out var count);
    
    // Create an array with the capacity to hold this many elements.
    var extensions = new string[count];
    
    // No nothing if it returned 0 result or an invalid address for the pointer to the array.
    if (count > 0 && ptr != IntPtr.Zero)
    {
        // Initialize the offset to 0, which is how far into the the array's address we are reading.
        var offset = 0;
        
        // Begin looping, breaking once we have process the number of elements in the array.
        // Which each iteration, we increase the offset by the size a pointer (4/8 bytes for 32/64 bit CPU)
        // This will place the offset at the beginning of the next element in the array.
        for (var i = 0; i < count; i++, offset += IntPtr.Size)
        {
            // Get the address stored at this location in the array. This address is to a null-terminated 
            // C "string"
            var p = Marshal.ReadIntPtr(ptr, offset);
            // Read the pointer as a string, and store it in our array. This is a copy operation, and the 
            // Marshal class stops when it hits a null-byte automatically.
            extensions[i] = Marshal.PtrToStringAnsi(p);
            
            // Move on to the next.
        }
    }
    // Totally superfluous and overkill (should never actually need to), but we return a copy of our array
    // rejecting any element that is null or empty.
    return extensions.Where(s => !string.IsNullOrWhiteSpace(s)).ToArray();
}

This all appears legit, even in testing, unless I am just missing something obvious (very possible). Would it be possible for you to clone and run this through a debugger with break-points and see exactly where the error is occurring? I am curious if it is not finding the address of the actual function, which causes the segfault, or if it is something in the C# code in that loop and misreading a pointer or something. I am unable to reproduce the error on my end to really be of much help at the moment. 
```

**Comment by rovecode** [comment]
> Oh, my bad, completely slipped my mind on this. I am literally digging into right now and working on it. Sorry for the delay :/

Sorry, i didn't see your answer. I think because you ask so fast :)

**Comment by rovecode** [comment]
> Well, am kinda already scratching my head on what the issue could be. I don't have Mac to test it on, but on my Arch LInux machine.
> 
> Running this code:
> 
> ```csharp
> static void Main(string[] args)
> {
>     Glfw.Init();
>     Console.WriteLine($"Vulkan: {Vulkan.IsSupported}");
>     foreach (var extension in Vulkan.GetRequiredInstanceExtensions())
>     {
>         Console.WriteLine(extension);
>     }
> }
> ```
> 
> ...gives me this:
> 
> ```
> Vulkan: True
> VK_KHR_surface
> VK_KHR_xcb_surface
> ```
> 
> I started digging into the code, and ensuring the methods was a proper analog of its C counterpart. 
> 
> The C methods is pretty straightforward:
> ```c
> const char** glfwGetRequiredInstanceExtensions(uint32_t *count);
> ```
> 
> You call it, it returns a pointer to a an array of pointers, and writes the number of elements in the array to `count` so you know how many elements to read without getting a segfault, which would cause the `AccessViolationException`. The return value is essentially an a pointer to an `IntPtr[]`, where each pointer in the array is a pointer to a null-terminated string.
> 
> The C# code of this library appears to handle this properly, even when stepping through it line by line. I annotated it all to explain the logic step-by-step (my process for finding bugs)
> 
> The private overload of the method it calls internally, doesn't appear like any problems here.
> 
> ```csharp
> [DllImport(Glfw.LIBRARY, EntryPoint = "glfwGetRequiredInstanceExtensions", CallingConvention = CallingConvention.Cdecl)]
> private static extern IntPtr GetRequiredInstanceExtensions(out uint count);
> ```
> 
> The actual method that does the main logic processing.
> 
> ```csharp
> public static string[] GetRequiredInstanceExtensions()
> {
>     // Get the initial pointer where the C array is located in memory, and how many elements there are.
>     var ptr = GetRequiredInstanceExtensions(out var count);
>     
>     // Create an array with the capacity to hold this many elements.
>     var extensions = new string[count];
>     
>     // No nothing if it returned 0 result or an invalid address for the pointer to the array.
>     if (count > 0 && ptr != IntPtr.Zero)
>     {
>         // Initialize the offset to 0, which is how far into the the array's address we are reading.
>         var offset = 0;
>         
>         // Begin looping, breaking once we have process the number of elements in the array.
>         // Which each iteration, we increase the offset by the size a pointer (4/8 bytes for 32/64 bit CPU)
>         // This will place the offset at the beginning of the next element in the array.
>         for (var i = 0; i < count; i++, offset += IntPtr.Size)
>         {
>             // Get the address stored at this location in the array. This address is to a null-terminated 
>             // C "string"
>             var p = Marshal.ReadIntPtr(ptr, offset);
>             // Read the pointer as a string, and store it in our array. This is a copy operation, and the 
>             // Marshal class stops when it hits a null-byte automatically.
>             extensions[i] = Marshal.PtrToStringAnsi(p);
>             
>             // Move on to the next.
>         }
>     }
>     // Totally superfluous and overkill (should never actually need to), but we return a copy of our array
>     // rejecting any element that is null or empty.
>     return extensions.Where(s => !string.IsNullOrWhiteSpace(s)).ToArray();
> }
> ```
> 
> This all appears legit, even in testing, unless I am just missing something obvious (very possible). Would it be possible for you to clone and run this through a debugger with break-points and see exactly where the error is occurring? I am curious if it is not finding the address of the actual function, which causes the segfault, or if it is something in the C# code in that loop and misreading a pointer or something. I am unable to reproduce the error on my end to really be of much help at the moment. 
> 
> 
> 
> 

Yeah, i will try in nears time debug and try reproduce this exception.

**Comment by rovecode** [comment]
Thanks again for your time!
