### ISSUE TITLE
Expunge references to "Game"

### ISSUE THREAD

**Issue by wyckster** [ForeverZer0/glfw-net#4]
There are plenty of applications for GLFW that are not games.  I suggest that classes that contain the word _**Game**_ be renamed to something more application agnostic.

Perhaps `GameWindow` could become `AppWindow`.

**Comment by ForeverZer0** [comment]
I had considered this, and at the time of originally writing it, I chose `GameWindow` as it was more along the lines of my original purpose for it, which was a part of larger 2-D game-engine framework, and it is more of an add-on/helper to the actual library.

I do agree that perhaps `AppWindow`, `NativeWindow`, etc. would be a more appropriate name for it. I will make this change with the change with the next major update that will use the new GLFW 3.3 backend.

**Comment by ForeverZer0** [comment]
`GameWindow` class has been aptly renamed to `NativeWindow`, and the `GLFW.Game` namespace has been migrated to the `GLFW` namespace.
