### ISSUE TITLE
GLFW doesn't initialize

### ISSUE THREAD

**Issue by Panthr75** [ForeverZer0/glfw-net#40]
GLFW downloaded from: https://github.com/glfw/glfw/releases/tag/3.3.2 (WINDOWS 64)

File setup
-> GameEngine.Core.exe
-> glfw.dll (renamed from glfw3.dll in zip at /lib-vc2019)
-> glfw.lib (renamed from glfw3.lib in zip at /lib-vc2019)
-> glfwdll.lib (renamed from glfw3dll.lib in zip at /lib-vc2019)

Crash:
![image](https://user-images.githubusercontent.com/29237603/107092999-1fd46500-67ca-11eb-8cba-4682b0568130.png)

**Comment by Panthr75** [comment]
Right now it appears to be resolved, but there may be more trouble down the line, as the solution was to change my build format from x86 to x64

**Comment by ForeverZer0** [comment]
The BadImageFormat means that the native DLL and managed assembly have mismatched CPU architecture (i.e. you are building x86 assembly, but referencing native x64 libraries, or vice-versa). GLFW offers binaries for both architectures, though your managed assembly will need to be built with the matching architecture. 

[32-bit Binaries](https://github.com/glfw/glfw/releases/download/3.3.2/glfw-3.3.2.bin.WIN32.zip)
[64-bit Binaries](https://github.com/glfw/glfw/releases/download/3.3.2/glfw-3.3.2.bin.WIN64.zip)

If you want to build your project for for x86, you would only need to get the native x86 DLL to make it work.

On a side note, the only binaries you need are the .dll ones, not the ones with .lib extension. The .lib files are mainly for static linking in C/C++, you only need the dynamic ones.
