### ISSUE TITLE
GLFW.Exception  WGL: OpenGL profile requested but WGL_ARB_create_context_profile is unavailable

### ISSUE THREAD

**Issue by RpxdYTX** [ForeverZer0/glfw-net#41]
it throws this exception when running, i found in stackoverflow that it may be that it is using OpenGL3.3 while my pc only has 3.1 but the original stackoverflow issue is in original glfw, what do i do to fix it using c# instead of c++?

**Comment by ForeverZer0** [comment]
If you hardware doesn't support that version of OpenGL, there isn't much that can be done that I am aware of. GLFW is just supplying a implementation and platform-agnostic front-end for context creation, the actual error occurs from the native OpenGL implementation when the system recognizes a version unsupported by the machine was requested. 

It might be possible that your hardware supports it, but the drivers are outdated, where updating them could fix the problem, though that is probably a long-shot. The next best scenario is enabling the functionality you need through extensions. Oftentimes functionality introduced between versions has wide support via extensions for a while before it is made "core", so you may have some luck being that it is only 2 minor revisions difference in what you request and what you actually have. Unfortunately this C# project is just a wrapper around the native C library, all the heavy lifting and most of the functionality is being performed by it.

**Comment by RpxdYTX** [comment]
oh ok then, about the driver stuff i checked and it is updated and only supports opengl 3.1, i will close the issue since it isn't with your project, i might also use the native lib or other c# graphic libs, thank you!
