### ISSUE TITLE
glTexImage2D throws System.AccessViolationException: 

### ISSUE THREAD

**Issue by theLemon505** [ForeverZer0/glfw-net#47]
no clue why this is happening but when i convert a System.Drawing image to a byte[] then to a IntPtr and pass it to this function, i get a System.AccessViolationException:

**Comment by theLemon505** [comment]
here the code

using System.Drawing;
using System.Drawing.Imaging;
using System.Runtime.InteropServices;
using static OpenGL.GL;

namespace TheRaft.Core.Graphics
{
    internal class Texture
    {
        public uint id;

        public unsafe Texture(string name)
        {
            string path = "C:/.TheRaft/Textures/" + name;
            Image i = Image.FromFile(path);
            byte[] data = (byte[])(new ImageConverter()).ConvertTo(i, typeof(byte[]));
            fixed (byte* p = data)
            {
                IntPtr ptr = (IntPtr)p;
                glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_MIRRORED_REPEAT);
                glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_MIRRORED_REPEAT);
                float[] borderColor = { 1.0f, 1.0f, 0.0f, 1.0f };
                fixed (float* pt = &borderColor[0]) {
                    glTexParameterfv(GL_TEXTURE_2D, GL_TEXTURE_BORDER_COLOR, pt);
                }
                glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
                glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
                id = glGenTexture();
                glBindTexture(GL_TEXTURE_2D, id);
                glTexImage2D(GL_TEXTURE_2D, 0, GL_RGB, i.Width, i.Height, 0, GL_RGB, GL_UNSIGNED_BYTE, ptr);
                glGenerateMipmap(GL_TEXTURE_2D);
            };
        }
    }
}

**Comment by theLemon505** [comment]
fixed, was not allocating the memory for the texture

**Comment by ForeverZer0** [comment]
Glad you got it figured out, but one word of warning if you are using the OpenGL bindings from the example project: 

They are not thoroughly tested nor even "officially" part of this project, were simply generated via a dirty script I wrote on a fixed GL version using the OpenGL registry, and were merely provided as convenience to test this project with. While they will likely suffice for most cases without any issue, I would not personally consider them production-ready, nor exactly the most user-friendly.
