### ISSUE TITLE
GLFW.Exception: Cannot set swap interval without a current OpenGL or OpenGL ES context

### ISSUE THREAD

**Issue by ameijboom** [ForeverZer0/glfw-net#48]
We're currently working on updating our university's game engine (GXP Engine) from using GLFW2 to GLFW3 using glfw-net, but whenever we try to run the engine now we get the following error.

This is the particular function where it gives the error, right on the Glfw.SwapInterval line
https://pastebin.com/bvkJRvhQ
		
We're using OpenTK to provide OpenGL and am running on Windows 10 w/ .NET 6

**Comment by ForeverZer0** [comment]
The context must be made current with a call to `glfwMakeContextCurrent` before you can set the swap interval, as per the native GLFW documentation:

https://www.glfw.org/docs/3.3/group__context.html#ga6d4e0cdf151b5e579bd67f13202994ed

>Errors 
Possible errors include GLFW_NOT_INITIALIZED, **GLFW_NO_CURRENT_CONTEXT** and GLFW_PLATFORM_ERROR..

As a rule of thumb I have always followed the general rule to have a call to `GLFW.MakeContextCurrent` be pretty much the first thing done after creating the window, as the overwhelming majority of the GLFW functions require a current context. You should typically be  following something that looks like this:

- Initialize GLFW, set window hints, set error callback, etc
- Create window with `GLFW.CreateWindow`
- Double-check that the returned handle is valid
- Set current context with `GLFW.MakeContextCurrent`
- Configure the rest of state, swap interval, load GL functions (depending on your GL bindings), etc.

Inserting `GLFW.MakeContextCurrent` under your window creation line should solve your issues.

```csharp
private static void Main(string[] args)
{
    GLFW.Init();
    GLFW.WindowHint(WindowHint.ContextVersionMajor, 3);
    GLFW.WindowHint(WindowHint.ContextVersionMinor, 3);
    GLFW.WindowHint(WindowHint.OpenGLProfile, OpenGLProfile.Core);
    GLFW.WindowHint(WindowHint.Doublebuffer, true);
    GLFW.WindowHint(WindowHint.Resizable, true);
    var context = GLFW.CreateWindow(1024, 768, "My Window", Monitor.None, Window.None);
    if (context == Window.None)
        throw new Exception("Failed to create a context, double-check the window hints are valid.");
    
    GLFW.MakeContextCurrent(context);
    GLFW.SwapInterval(1);
   
    GL.Load(GLFW.GetProcAddress);

    while (!GLFW.WindowShouldClose(context))
    {
        GLFW.PollEvents();
        GL.Clear(ClearBufferMask.Color);
        GLFW.SwapBuffers(context);
    }
    
    GLFW.DestroyWindow(context);
    GLFW.Terminate();
}
```

The example code is from a modified version of the library I have in a current project, so some of the naming conventions may be different, but you can hopefully see what they are analogous to.
